name: taktik
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.7+28

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS stili ikonlar için
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.1.0

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  cloud_functions: ^5.0.1
  firebase_app_check: ^0.3.1+2
  firebase_messaging: ^15.0.3
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3

  # Bildirimlerin foreground'da gösterimi için
  flutter_local_notifications: ^17.2.1

  # Grafikler
  fl_chart: ^0.68.0
  confetti: ^0.7.0
  lottie: ^3.1.2
  url_launcher: ^6.3.1

  # Font
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1

  http: ^1.2.1
  flutter_markdown: ^0.7.1
  cached_network_image: ^3.4.1
  file_picker: ^8.0.3
  flutter_math_fork: ^0.7.2
  markdown: ^7.2.2

  # BENZERSİZ ID İÇİN EKLENDİ
  uuid: ^4.4.0
  crypto: ^3.0.3
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2

  # Paylaşım ve XFile
  share_plus: ^11.1.0
  cross_file: ^0.3.4
  shared_preferences: ^2.5.3

  # Ekranı açık tutmak için
  wakelock_plus: ^1.2.7

  collection: any

  # RevenueCat
  purchases_flutter: ^9.7.1

  # Environment variables for secure API key management
  flutter_dotenv: ^5.1.0

  # Google AdMob
  google_mobile_ads: ^6.0.0

  # In-App Review
  in_app_review: ^2.0.10

  # Connectivity
  connectivity_plus: ^6.1.2
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.4

# Ana Flutter yapılandırması
flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/prompts/
    - assets/images/
    - assets/lotties/
    - .env

# Splash Screen Ayarları
flutter_native_splash:
  color: "#0F172A"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#0F172A"
  android: true
  ios: true
  web: false
  fullscreen: true
  color_dark: "#0F172A"
  image_dark: assets/images/logo.png

# --- EKLENEN KISIM BURASI ---
# Uygulama İkonu Ayarları
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true # Bu satır App Store şeffaflık hatasını çözer!